-- 코드를 입력하세요
SELECT CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * (1 - (DISCOUNT_RATE / 100)) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE CAR_ID NOT IN (SELECT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE OR '2022-11-30' BETWEEN START_DATE AND END_DATE)
GROUP BY CAR_ID
HAVING CAR_TYPE IN ('세단', 'SUV') AND FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC