-- 코드를 입력하세요
WITH DURATION AS (
SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) AS DURATION,
    CASE WHEN DATEDIFF(END_DATE, START_DATE) >= 90 THEN '90일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) >= 30 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) >= 7 THEN '7일 이상'
    ELSE 'X' END AS TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT HISTORY_ID, ROUND(DAILY_FEE * (DURATION + 1) * (1 - (CASE WHEN DISCOUNT_RATE IS NULL THEN 0 ELSE DISCOUNT_RATE END / 100)),0) AS FEE
FROM DURATION AS D
INNER JOIN CAR_RENTAL_COMPANY_CAR AS C
ON C.CAR_ID = D.CAR_ID AND CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON TYPE = DURATION_TYPE AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC